{% set name = "ezgmail" %}
{% set version = "2022.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EZGmail-{{ version }}.tar.gz
  sha256: f238c28dd79d69cb44b88e3b6f061c6a9d678ee8e567317a26eb869021b813fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - google-api-python-client
    - oauth2client

test:
  imports:
    - ezgmail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/ezgmail
  summary: A Pythonic interface to the Gmail API that actually works as of February 2022.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
