{% set name = "ezgmail" %}
{% set version = "2024.8.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EZGmail-{{ version }}.tar.gz
  sha256: d9a36fca2fec72c8bb19307f3ef1bed7a98ae93bb3ebf87b550b6b837f951c6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - google-api-python-client
    - google-auth-oauthlib

test:
  imports:
    - ezgmail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/ezgmail
  summary: A Pythonic interface to the Gmail API that actually works as of February 2022.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
