{% set name = "ezgmail" %}
{% set version = "2024.8.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a40c92de115290cf64e7f7fd4c59e136c49b89593ff82155bf65edf0dfa2f7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - google-api-python-client
    - google-auth-oauthlib

test:
  imports:
    - ezgmail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/ezgmail
  summary: A Pythonic interface to the Gmail API that actually works as of February 2022.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
