{% set name = "ezgmail" %}
{% set version = "2024.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b046476e8b6c633c31fc0f2ed8b28df8956c736fea1094b336ce5a92b37c0a5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-python-client
    - google-auth-oauthlib
    - google-auth-httplib2

test:
  imports:
    - ezgmail
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asweigart/ezgmail
  summary: A Pythonic interface to the Gmail API that actually works as of February 2022.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
